swagger: '2.0'
info:
  title: 3D-Map Tiles API
  description: Enhance your geospatial application with 3D-maps
  version: "1.0.0"
# the domain of the service
host: 130.206.80.175
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /api/3d-map-tiles
produces:
  - application/xml+xml3d
  - image/jpeg
  - image/png
parameters:
  provider:
    name: provider
    description: Name of the configuration
    in: path
    required: true
    type: string
  z:
    name: z
    description: Level of detail
    in: path
    required: true
    type: integer
    format: int32
    minimum: 0
    maximum: 20
  x:
    name: x
    description: Tile index along x-axis
    in: path
    required: true
    type: integer
    format: int32
    minimum: 0
  y:
    name: y
    description: Tile index along y-axis
    in: path
    required: true
    type: integer
    format: int32
    minimum: 0

paths:
# /{provider}/{z}/{x}/{y}-model.xml:
  /{provider}/{z}/{x}/{y}.xml:
    get:
      summary: Model references to be included into the DOM's 3D scene
      parameters:
        - $ref: '#/parameters/provider'
        - $ref: '#/parameters/z'
        - $ref: '#/parameters/x'
        - $ref: '#/parameters/y'
      produces:
        - application/xml+xml3d
      responses:
        200:
          description: One model tag per layer of the tile
        304:
          description: Use cached version of the tile

  /{provider}/{z}/{x}/{y}-asset.xml:
    get:
      summary: Tile's assets
      parameters:
        - $ref: '#/parameters/provider'
        - $ref: '#/parameters/z'
        - $ref: '#/parameters/x'
        - $ref: '#/parameters/y'
      produces:
        - application/xml+xml3d
      responses:
        200:
          description: One asset tag per layer of the tile containing one or more assetmesh tags
        304:
          description: Use cached version of the tile


  /{provider}/{z}/{x}/{y}-texture.png:
    get:
      summary: Texture used in the tile's assets
      parameters:
        - $ref: '#/parameters/provider'
        - $ref: '#/parameters/z'
        - $ref: '#/parameters/x'
        - $ref: '#/parameters/y'
      produces:
        - image/png
      responses:
        200:
          description: Image texture referenced from the tile's asset
        304:
          description: Use cached version of the tile's image texture
        404:
          description: Backend does not utilize an image texture

